#!/bin/bash

#### GENERIC SETUP
. /dmt3/software/spearmint/spearmint/generic/gpmin-setup.bash

if  [ -z "$1" ]
then 
    args='.'
else
    args=${@:1}
fi

### CHECK THE NUMBER OF COMNMAND LINE ARUGMENTS; 1 REQUIRED
if [ "$1" == "-h" -o  "$1" == "-help" -o  "$1" == "--help" -o ! -d "${args[0]}" -o ! -f "${args[0]}/SGE_JOB_ID" ] 
then
    name=`basename $0`
    echo "Usage: 
    $name [DIR1] [DIR2] [DIR3] ...

DIRs must be valid gpmin experiment directories.
If no directory is given, then the current directory is considered.  

"
    exit
fi

args=`realpath $args`

gpmin_stop $args

