#!/bin/bash

### GENERIC SETUP
. /dmt3/software/spearmint/spearmint/generic/gpmin-setup.bash

args=`realpath  ${@:1}`

### CHECK THE NUMBER OF COMNMAND LINE ARUGMENTS; 2 REQUIRED
if [ "$#" -lt "1"    -o "$1" == "-h" -o  "$1" == "-help" -o  "$1" == "--help" -o ! -d "$1"  ] 
then
    name=`basename $0`
    echo "Usage: 
    $name DIR1 [DIR2] [DIR3] ...
    
The first argument is compulsory. 

DIRs must be valid gpmin experiment directories. 

"
    exit
fi


ROW_PATTERN="%-42s%-10s%-11s%-11s%-8s%-20s\n"

LINE='#'`printf %98s |tr " " "-"`'#'

echo $LINE
printf $ROW_PATTERN  '' '' 'DURATION' ' BEST' 'BEST' 'CANDIDATES '  
printf $ROW_PATTERN  'EXPERIMENT' 'STATUS' '(hh:mm)' ' VALUE' 'JOB_ID' ': COMPLETED' 
printf $ROW_PATTERN  '' '' '' '' '' ': PENDING' 
echo $LINE

for dir in $args
do 
    if [ ! -d "$dir" -o ! -f "$dir/trace.csv" -o ! -f "$dir/SGE_JOB_ID"  ] 
    then
        printf "%-42s%s\n" $dir "Not started or not a valid directory."
        continue
    fi
    FIRST=($(head -n 1 $dir/trace.csv | tr ',' '\n'))
    STATUS=($(tail -n 1 $dir/trace.csv | tr ',' '\n'))
    hh=$(echo  "(${STATUS[0]} - ${FIRST[0]}) / 3600" | bc -l )
    mm=$(echo '0.'`echo "$hh" | cut -d '.' -f 2`" * 60" | bc -l | cut -d '.' -f 1 )
    if [ -z "$mm" ] 
    then 
        mm="00"
    fi
    if [ `expr length "$mm"` -lt 2 ] 
    then 
        mm="0"$mm
    fi
    hh=$(echo "$hh" | cut -d '.' -f 1)
    if [ -z "$hh" ] 
    then 
        hh="00"
    fi
    
    JOB_ID=`cat $dir/SGE_JOB_ID` 
   
    STAT=`print_job_status $JOB_ID`

    #printf "%-10s\t%s\n"  
    printf $ROW_PATTERN "`basename $dir`" $STAT " $hh:$mm"  ${STATUS[1]}  ${STATUS[2]}  "${STATUS[3]} : ${STATUS[5]} : ${STATUS[4]}"
done
echo $LINE

