#!/bin/bash

if  [ -z "$1" ]
then 
    arg=`realpath '.'`
else
    ### CHECK THE NUMBER OF COMNMAND LINE ARUGMENTS; 1 REQUIRED
    if [  "$1" == "-h" -o  "$1" == "-help" -o  "$1" == "--help"  ] 
    then
        name=`basename $0`
        echo "Usage: 
        $name [DIR] 

    DIRs must be valid gpmin experiment directories.
    If no directory is given, then the current directory is considered.  

    "
        exit
    fi

    arg=`realpath  $1`
fi 

tail -n 100 -f $arg/gpmin.log

