#!/bin/bash

### CHECK THE NUMBER OF COMNMAND LINE ARUGMENTS; 2 REQUIRED
if [ "$#" -lt "1"    -o "$1" == "-h" -o  "$1" == "-help" -o  "$1" == "--help" -o ! -d "$1" -o ! -f "$1/trace.csv" ] 
then
    name=`basename $0`
    echo "Usage: 
    $name CONFIG-FILE DIR1 [DIR2] [DIR3] ...
    
The first argument is compulsory. 

DIRs must be valid gpmin experiment directories. 

"
    exit
fi

for dir in ${*:1}
do 
    if [ -d "$dir" -a -f "$dir/trace.csv" ] 
    then
        FIRST=($(head -n 1 $dir/trace.csv | tr ',' '\n'))
        STATUS=($(tail -n 1 $dir/trace.csv | tr ',' '\n'))
        hh=$(echo  "(${STATUS[0]} - ${FIRST[0]}) / 3600" | bc -l )
        mm=$(echo '0.'`echo "$hh" | cut -d '.' -f 2`" * 60" | bc | cut -d '.' -f 1 )
        hh=$(echo "$hh" | cut -d '.' -f 1)
         
        echo
        echo 'EXPERIMENT:   ' `basename $dir`
        echo 'TIME (hh:mm): ' "$hh:$mm"
        echo 'BEST VALUE:   ' ${STATUS[1]}
        echo 'BEST JOB_ID:  ' ${STATUS[2]}
        echo 'CANDIDATES:   ' ${STATUS[3]}
        echo 'PENDING:      ' ${STATUS[4]}
        echo 'COMPLETED:    ' ${STATUS[5]}
    fi
done

