#!/bin/bash

### TODO: move to permanent location
GPMIN_HOME=/Users/andreirusu/projects/spearmint/spearmint/generic

### CHECK THAT THE FIRST ARGUMENT IS AN EXISTING FILE
if [[ "$#" -ge "1" ]] 
then
    DATE=$(date +".%Y.%m.%d.%H.%M.%S")
    EXP_DIR=$0$DATE 
    mkdir -p  $EXP_DIR   
    # put together a working directory for spearmint 
    cp $1 $EXP_DIR
    cp $GPMIN_HOME/job.py $EXP_DIR
    cp $GPMIN_HOME/job.sh $EXP_DIR
    cd $EXP_DIR
    echo "Current experiment: "$PWD
else
    echo 'Specify the path to a config file!'
    exit
fi

echo 'Status: '
crunch -b y 'python spearmint.py --method=GPEIOptChooser --max-concurrent=1 --max-finished-jobs=0 --grid-seed=1 `dirname $1`'

