#!/bin/bash


### CHECK THAT THE FIRST ARGUMENT IS AN EXISTING FILE
if [[ "$#" -ge "1" ]] 
then
    DATE=$(date +".%Y.%m.%d.%H.%M")
    EXP_DIR=$0$DATE 
    mkdir -p  $EXP_DIR   
    # copy config file in directory 
    cp $1 $EXP_DIR
    cd $EXP_DIR
    echo "Current experiment: "$PWD
else
    echo 'Specify the path to a config file!'
    exit
fi

#python spearmint.py --method=GPEIOptChooser --max-concurrent=10 --max-finished-jobs=1000 --grid-seed=1 `dirname $0`
